import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import com.paysetu.app.data.ledger.LedgerRepository
import com.paysetu.app.data.ledger.entity.LedgerTransactionEntity
import com.paysetu.app.data.ledger.entity.TransactionDirection
import com.paysetu.app.data.ledger.entity.TransactionStatus
import com.paysetu.app.ui.payment.PaymentUiState
import java.util.UUID


class PaymentViewModel(
    private val ledgerRepository: LedgerRepository
) : ViewModel() {

    private val _uiState = MutableStateFlow<PaymentUiState>(PaymentUiState.Idle)
    val uiState: StateFlow<PaymentUiState> = _uiState

    fun sendOfflinePayment(
        amount: Long,
        prevTxHash: ByteArray?
    ) {
        viewModelScope.launch {
            _uiState.value = PaymentUiState.Processing

            try {
                val tx = LedgerTransactionEntity(
                    id = 0L, // auto-generated by Room

                    txHash = UUID.randomUUID().toString().toByteArray(),
                    prevTxHash = prevTxHash ?: ByteArray(0),

                    senderDeviceId = "LOCAL_DEVICE".toByteArray(),
                    receiverDeviceId = "REMOTE_DEVICE".toByteArray(),

                    amount = amount,
                    timestamp = System.currentTimeMillis(),

                    signature = ByteArray(0), // Phase 10 will replace this

                    direction = TransactionDirection.OUTGOING,

                    status = TransactionStatus.ACCEPTED
                )





                ledgerRepository.appendTransactionAtomically(tx)

                _uiState.value = PaymentUiState.Success(
                    txHash = tx.txHash.decodeToString()
                )

            } catch (e: Exception) {
                _uiState.value = PaymentUiState.Failure(
                    reason = e.message ?: "Unknown error"
                )
            }
        }
    }

    fun reset() {
        _uiState.value = PaymentUiState.Idle
    }
}
