package com.paysetu.app.ui.payment

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Done
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable
fun ReceivePaymentScreen(
    viewModel: PaymentViewModel,
    onAccept: () -> Unit,
    onReject: () -> Unit
) {
    val uiState by viewModel.uiState.collectAsState()
    // 💡 PHASE 14: Collect the Session ID generated by the ViewModel
    val sessionId by viewModel.myQrSessionId.collectAsState()

    // 💡 Generate the QR bitmap only when the sessionId changes
    val qrBitmap = remember(sessionId) {
        sessionId?.let { QrCodeGenerator.generateQrCode(it) }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        when (uiState) {
            is PaymentUiState.Idle -> {
                Text(
                    text = "Receive Offline Payment",
                    fontSize = 22.sp,
                    fontWeight = FontWeight.Bold
                )

                Spacer(modifier = Modifier.height(24.dp))

                // 💡 PHASE 14: Display the QR Code
                if (qrBitmap != null) {
                    Card(
                        elevation = CardDefaults.cardElevation(4.dp),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = Color.White)
                    ) {
                        Image(
                            bitmap = qrBitmap.asImageBitmap(),
                            contentDescription = "Payment QR Code",
                            modifier = Modifier
                                .size(250.dp)
                                .padding(16.dp)
                        )
                    }

                    Spacer(modifier = Modifier.height(16.dp))

                    // Display the text ID as a fallback
                    Text(
                        text = "ID: $sessionId",
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.primary
                    )
                } else {
                    CircularProgressIndicator(modifier = Modifier.size(48.dp))
                }

                Spacer(modifier = Modifier.height(24.dp))

                Text(
                    text = "Broadcasting...",
                    fontSize = 16.sp,
                    fontWeight = FontWeight.Medium,
                    color = Color.DarkGray
                )
                Text(
                    text = "Ask the sender to scan this QR code",
                    color = Color.Gray,
                    fontSize = 14.sp
                )

                Spacer(modifier = Modifier.height(32.dp))

                Button(
                    onClick = {
                        viewModel.stopOfflineMode()
                        onReject()
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = Color.LightGray)
                ) {
                    Text("Cancel", color = Color.Black)
                }
            }

            is PaymentUiState.Processing -> {
                Text("Verifying Transaction...", fontSize = 18.sp)
                LinearProgressIndicator(modifier = Modifier.fillMaxWidth().padding(top = 16.dp))
            }

            is PaymentUiState.Success -> {
                val hash = (uiState as PaymentUiState.Success).txHash
                Icon(
                    imageVector = Icons.Default.Done,
                    contentDescription = null,
                    tint = Color(0xFF4CAF50),
                    modifier = Modifier.size(64.dp)
                )
                Spacer(modifier = Modifier.height(16.dp))
                Text("Payment Received!", fontSize = 24.sp, fontWeight = FontWeight.Bold)
                Text("Hash: ${hash.take(12)}...", color = Color.Gray)

                Spacer(modifier = Modifier.height(32.dp))

                Button(onClick = onAccept, modifier = Modifier.fillMaxWidth()) {
                    Text("View in Ledger")
                }
            }

            is PaymentUiState.Failure -> {
                Text("Payment Failed", color = Color.Red, fontSize = 20.sp)
                Text((uiState as PaymentUiState.Failure).reason)
                Spacer(modifier = Modifier.height(16.dp))
                Button(onClick = { viewModel.reset() }) {
                    Text("Try Again")
                }
            }
        }
    }
}